### ISSUE TITLE
Sample Code License?

### ISSUE THREAD

**Issue by japostoles** [yshrkt/VuforiaSampleSwift#27]
Hello, I was wondering what the license is for the sample code you've created?  Are we able to use your VuforiaManager in our own projects?

Can you give some guidance on whether your code is open source or not?

**Comment by yshrkt** [comment]
Hi, @japostoles

> Are we able to use your VuforiaManager in our own projects?

Yes, You can use freely. 
I am thinking this sample is still not production level at the current level.
So, You maybe need to modifying code for your projects.

> Can you give some guidance on whether your code is open source or not?

This sample is open source.
I wasn't considered about license, because this is sample code...
I'm thinking that It's the best that anyone can use freely this sample code as possible.
Therefore, I set this sample as MIT License now.
